$(`${'<form name="jump">\r\n<div class="MyColors">\r\n					<map id="ColorsMap" name="ColorsMap">\r\n					<area alt="" coords="270, 0, 295, 25" href="javascript:chooseStyle(\'none\',60)" shape="rect" title="1">\r\n					<area alt="" coords="239, 0, 265, 25" href="javascript:chooseStyle(\'Co2\',60)" shape="rect" title="2">\r\n					<area alt="" coords="209, 0, 235, 25" href="javascript:chooseStyle(\'Co3\',60)" shape="rect" title="3">\r\n					<area alt="" coords="178, 0, 203, 25" href="javascript:chooseStyle(\'Co4\',60)" shape="rect" title="4">\r\n					<area alt="" coords="148, 0, 173, 25" href="javascript:chooseStyle(\'Co5\',60)" shape="rect" title="5">\r\n					</map>\r\n			        <img alt="" height="40" src="" width="300" usemap="#ColorsMap"></div>\r\n</form>\r\n\r\n\r\n   \r\n\r\n'}`).insertBefore(".nav-tabs");
$.getScript("https://cdn.statically.io/gh/mmnm399819/dimask98/master/Sham1.js");
$(".u-pic").css("border-radius", "3px");
$(".hand.nosel.fl.uzr.border").css({margin: "1px 0", paddingTop: "2px", borderRadius: "5px"});
$(".uzr.fl.corner.borderg").css({margin: "0px 0", paddingTop: "2px", borderRadius: "5px"});
$(".checkbox label").html(`${'<input id="stealth" type="checkbox" value="" maxlength="12"><i class="fa fa-eye-slash" aria-hidden="true">'}`);
$(".nav-tabs").addClass("fl").css("width", "100%");
$(".nav-tabs").addClass("fl").css("width", "100%");
$(`${'<link rel="stylesheet" type="text/css" href="">\r\n\r\n\r\n<link href="https://cdn.statically.io/gh/mmnm399819/dimask98/master/Sham22.css" rel="stylesheet" type="text/css" />\r\n<link href="https://cdn.statically.io/gh/mmnm399819/dimask98/master/Sham3.css" media="screen" rel="alternate stylesheet" title="Co2" type="text/css" />\r\n<link href="https://cdn.statically.io/gh/mmnm399819/dimask98/master/Sham4.css" media="screen" rel="alternate stylesheet" title="Co3" type="text/css" />\r\n<link href="https://cdn.statically.io/gh/mmnm399819/dimask98/master/Sham5.css" media="screen" rel="alternate stylesheet" title="Co4" type="text/css" />\r\n<link href="https://cdn.statically.io/gh/mmnm399819/dimask98/master/Sham6.css" media="screen" rel="alternate stylesheet" title="Co5" type="text/css" />\r\n\r\n<style>\r\n\r\n.MyColors {\r\n    position: absolute;\r\n    transform: matrix(1, 0, 0, 1, 72, -2);\r\n    margin-top: 2px;\r\n    width: 300px;\r\n    height: 60px;\r\n    float: right;\r\n    background: transparent url(https://cdn.statically.io/gh/mmnm399819/dimask98/master/PicsArt_05-16-05.09.06.png) no-repeat scroll right top;\r\n    text-align: left;\r\n}\r\n\r\n\r\n\r\n#des0 {\r\n    background-color: #3c3c3c;\r\n	border-radius: 15px 15px 0px 0!important;\r\n}\r\n\r\na.fa.fa-user-plus {\r\n    color: #ff0000;\r\n}\r\n\r\n\r\nlabel.fl.nosel.label.pnhead {\r\nbackground-image: -webkit-linear-gradient(45deg,hsla(0,0%,100%,.2) 25%,transparent 0,transparent 50%,hsla(0,0%,100%,.2) 0,hsla(0,0%,100%,.2) 75%,transparent 0,transparent)!important;\r\n\r\n}\r\n\r\n\r\n\r\n\r\n#des3 {\r\n    margin: 1px!important;\r\n}\r\n\r\nul.nav.nav-tabs.fl {\r\n    margin-top: 1px!important;\r\n}\r\n\r\n\r\n\r\n\r\n</style>\r\n'}`).insertBefore("body");

